name: Package

on:
  pull_request:
    types:
      - labeled

permissions:
  contents: write
  packages: write
  pull-requests: write

jobs:
  release-by-labeled:
    uses: serendie/.github/.github/workflows/package.yml@main
    secrets: inherit
