name: Release package

on:
  workflow_dispatch:
    inputs:
      increment:
        description: "Increment"
        required: true
        default: "patch"
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ssh-key: ${{ secrets.DEPLOY_KEY }}
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Setup Git User
        shell: bash
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "GitHub Actions"
      - run: npm ci
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Release
        run: npm run release --ci --increment ${{ github.event.inputs.increment }}
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
