name: Release Pull Request

on:
  push:
    branches: [main]

permissions:
  contents: read
  pull-requests: write

jobs:
  create:
    uses: serendie/.github/.github/workflows/release-pull-request.yml@main
    secrets: inherit
